In [1]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y

In [2]:


import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [3]:
df = pd.read_csv("../input/data.csv")

In [4]:
df.head()

   Unnamed: 0      ID       ...       GKReflexes  Release Clause
0           0  158023       ...              8.0         €226.5M
1           1   20801       ...             11.0         €127.1M
2           2  190871       ...             11.0         €228.1M
3           3  193080       ...             94.0         €138.6M
4           4  192985       ...             13.0         €196.4M

[5 rows x 89 columns]

In [5]:
df = df.astype(str)

In [6]:
df.dtypes

Unnamed: 0                  object
ID                          object
Name                        object
Age                         object
Photo                       object
Nationality                 object
Flag                        object
Overall                     object
Potential                   object
Club                        object
Club Logo                   object
Value                       object
Wage                        object
Special                     object
Preferred Foot              object
International Reputation    object
Weak Foot                   object
Skill Moves                 object
Work Rate                   object
Body Type                   object
Real Face                   object
Position                    object
Jersey Number               object
Joined                      object
Loaned From                 object
Contract Valid Until        object
Height                      object
Weight                      object
LS                          object
ST                          object
                             ...
Dribbling                   object
Curve                       object
FKAccuracy                  object
LongPassing                 object
BallControl                 object
Acceleration                object
SprintSpeed                 object
Agility                     object
Reactions                   object
Balance                     object
ShotPower                   object
Jumping                     object
Stamina                     object
Strength                    object
LongShots                   object
Aggression                  object
Interceptions               object
Positioning                 object
Vision                      object
Penalties                   object
Composure                   object
Marking                     object
StandingTackle              object
SlidingTackle               object
GKDiving                    object
GKHandling                  object
GKKicking                   object
GKPositioning               object
GKReflexes                  object
Release Clause              object
Length: 89, dtype: object

In [7]:
def nospace(name):
    name = name.split(" ")
    name = "_".join(name)
    return name

In [8]:

new_columns = list(map(nospace,df.columns))

In [9]:
df.columns = new_columns

In [10]:
df.columns

Index(['Unnamed:_0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag',
       'Overall', 'Potential', 'Club', 'Club_Logo', 'Value', 'Wage', 'Special',
       'Preferred_Foot', 'International_Reputation', 'Weak_Foot',
       'Skill_Moves', 'Work_Rate', 'Body_Type', 'Real_Face', 'Position',
       'Jersey_Number', 'Joined', 'Loaned_From', 'Contract_Valid_Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving', 'GKHandling',
       'GKKicking', 'GKPositioning', 'GKReflexes', 'Release_Clause'],
      dtype='object')

In [11]:
skills = df.columns[54:88].tolist()

In [12]:
df = df.loc[:,['Name','Age','Overall','Potential','Value','International_Reputation',
             'Skill_Moves','Position',*skills]]

In [13]:
df.columns

Index(['Name', 'Age', 'Overall', 'Potential', 'Value',
       'International_Reputation', 'Skill_Moves', 'Position', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving', 'GKHandling',
       'GKKicking', 'GKPositioning', 'GKReflexes'],
      dtype='object')

In [14]:
df.head(5)

                Name Age Overall    ...     GKKicking GKPositioning GKReflexes
0           L. Messi  31      94    ...          15.0          14.0        8.0
1  Cristiano Ronaldo  33      94    ...          15.0          14.0       11.0
2          Neymar Jr  26      92    ...          15.0          15.0       11.0
3             De Gea  27      91    ...          87.0          88.0       94.0
4       K. De Bruyne  27      91    ...           5.0          10.0       13.0

[5 rows x 42 columns]

In [18]:
df_print = df.loc[:,['Name','Age','Overall','Potential','Value','International_Reputation',
             'Skill_Moves','Position',*skills[0:2]]]
df_print.head(5)

                Name Age Overall    ...    Position Crossing Finishing
0           L. Messi  31      94    ...          RF     84.0      95.0
1  Cristiano Ronaldo  33      94    ...          ST     84.0      94.0
2          Neymar Jr  26      92    ...          LW     79.0      87.0
3             De Gea  27      91    ...          GK     17.0      13.0
4       K. De Bruyne  27      91    ...         RCM     93.0      82.0

[5 rows x 10 columns]

In [33]:
df_print_2 = df.loc[:,[*skills[2:11]]]
df_print_2.head(5)

  HeadingAccuracy ShortPassing     ...      BallControl Acceleration
0            70.0         90.0     ...             96.0         91.0
1            89.0         81.0     ...             94.0         89.0
2            62.0         84.0     ...             95.0         94.0
3            21.0         50.0     ...             42.0         57.0
4            55.0         92.0     ...             91.0         78.0

[5 rows x 9 columns]

In [35]:
df_print_3 = df.loc[:,[*skills[11:21]]]
df_print_3.head(5)

  SprintSpeed Agility Reactions    ...     Strength LongShots Aggression
0        86.0    91.0      95.0    ...         59.0      94.0       48.0
1        91.0    87.0      96.0    ...         79.0      93.0       63.0
2        90.0    96.0      94.0    ...         49.0      82.0       56.0
3        58.0    60.0      90.0    ...         64.0      12.0       38.0
4        76.0    79.0      91.0    ...         75.0      91.0       76.0

[5 rows x 10 columns]

In [37]:
df_print_4 = df.loc[:,[*skills[21:30]]]
df_print_4.head(5)

  Interceptions Positioning   ...    SlidingTackle GKDiving
0          22.0        94.0   ...             26.0      6.0
1          29.0        95.0   ...             23.0      7.0
2          36.0        89.0   ...             33.0      9.0
3          30.0        12.0   ...             13.0     90.0
4          61.0        87.0   ...             51.0     15.0

[5 rows x 9 columns]

In [38]:
df_print_5 = df.loc[:,[*skills[30:]]]
df_print_5.head(5)

  GKHandling GKKicking GKPositioning GKReflexes
0       11.0      15.0          14.0        8.0
1       11.0      15.0          14.0       11.0
2        9.0      15.0          15.0       11.0
3       85.0      87.0          88.0       94.0
4       13.0       5.0          10.0       13.0

In [ ]:
def get_value(s):
    
    last = s[-1]
    s = s[1:-1]
    try:
        val = float(s)
    except:
        return 0.0
    
    if last == 'M':
        val = val * 1000000.0
    if last == 'K':
        val = val * 1000.0
    return val

In [ ]:
df['Value'] = df['Value'].apply(get_value)

In [ ]:
df.head(5)

In [ ]:
df = df.dropna(subset = ['Value'])

In [ ]:
df.shape

In [ ]:
df = df[df['Value']!=0]

In [ ]:
df.shape

In [ ]:
def Pos(s):
    if s is None:
        return None
    if 'G' in s:
        return 1.0
    if 'B' in s:
        return 2.0
    if 'M' in s:
        return 3.0
    if 'W' in s:
        return 4.0
    if 'S' in s or 'F' in s:
        return 5.0

In [ ]:
df.head()

In [ ]:
df.dtypes

In [ ]:
df['Position'] = df['Position'].apply(Pos)

In [ ]:
df.dtypes

In [ ]:
df.head(5)

In [ ]:
df.loc[:,['Name','Value','Position']].head(5)

In [ ]:
def avg_best(scores):
    num_skills=5
    while None in scores:
        scores.remove(None)
    if len(scores)==0:
        return None
    elif len(scores)< num_skills:
        num_skills = len(scores)
    scores = list(map(float,scores))
    scores.sort()
    scores.reverse()
    scores = scores[0:num_skills]
    return sum(scores)/num_skills

In [ ]:
df['avg_best'] = df.apply(lambda row: avg_best([row[col] for col in skills]),axis=1)

In [ ]:
df = df.drop(columns=skills)

In [ ]:
df.columns

In [ ]:
df.loc[:,["Name","Value","Position","avg_best"]].head(5)

In [ ]:
df.dtypes

In [ ]:
cols = df.columns.tolist()
cols.remove('Name')
cols.remove('Value')

In [ ]:
df[cols] = df[cols].astype(float)

In [ ]:
df.dtypes

In [ ]:
df.head(5)

In [ ]:
df[cols].median(axis=0)

In [ ]:
med_df = df[cols].median(axis=0)
med_df['Age']

In [ ]:
med_dict = {}
for col in cols:
    med_dict[col] = med_df[col]
med_dict

In [ ]:
df.isnull().sum()

In [ ]:
df = df.fillna(value=med_dict)

In [ ]:
df.isnull().sum()

In [ ]:
df.head(5)

In [ ]:
df_sample = df.sample(frac=0.2,replace=False)

In [ ]:
df_sample.shape

In [ ]:
import matplotlib.pyplot as plt
ov_list = df_sample['Overall'].tolist()
val_list = df_sample['Value'].tolist()
plt.scatter(ov_list,val_list)
plt.show()

In [ ]:
msk = np.random.rand(len(df)) < 0.95
train = df[msk]
test = df[~msk]

In [ ]:
df.shape,train.shape,test.shape,17955*0.95

In [ ]:
feat_cols = cols
feat_cols

In [ ]:
train['features'] = df.apply(lambda row: [row[col] for col in feat_cols],axis=1)
train.head(5)

In [ ]:
test['features'] = df.apply(lambda row: [row[col] for col in feat_cols],axis=1)

In [ ]:
test.head(5)

In [ ]:
X_train = np.array(train['features'].tolist())
X_test = np.array(test['features'].tolist())
X_train.shape, X_test.shape

In [ ]:
Y_train = np.array(train['Value'])
Y_test = np.array(test['Value'])
Y_train.shape, Y_test.shape

In [ ]:
from sklearn.ensemble import RandomForestRegressor
regr = RandomForestRegressor(max_depth=30, 
                            n_estimators=40)

In [ ]:
regr.fit(X_train,Y_train)

In [ ]:
train_pred = regr.predict(X_train)

In [ ]:
train['pred']  = train_pred

In [ ]:
train.head(5)

In [ ]:
test_pred = regr.predict(X_test)

In [ ]:
test['pred']  = test_pred

In [ ]:
test.head(5)

In [ ]:
N_train = len(Y_train)
N_test = len(Y_test)
N_train,N_test

In [ ]:
rmse_train = np.sqrt(np.sum((Y_train-train_pred)**2)/N_train)
rmse_train

In [ ]:
rmse_test = np.sqrt(np.sum((Y_test-test_pred)**2)/N_test)
rmse_test

In [ ]:
val_list = test['Value'].tolist()
pred_list = test['pred'].tolist()
plt.scatter(val_list,pred_list)
plt.scatter(val_list,val_list,c='red')
plt.show()